site_name: Awesome Pelican
site_url: http://awesome-pelican.tk
site_description: A curated list of awesome projects related to Pelican, static-site generator
site_author: Khaled Monsoor
repo_url: https://github.com/kmonsoor/awesome-pelican
theme: flatly
google_analytics: ['UA-90237732-2', 'auto']
pages:
  - "Life is short, you need Python.": "index.md"

